title: Diablo Blockchain Benchmark
theme: jekyll-theme-slate
description: The website of the Diablo blockchain benchmark
github:
  zip_url: https://github.com/NatoliChris/diablo-benchmark/archive/refs/heads/v2.zip
  another_url: https://github.com/NatoliChris/diablo-benchmark/tree/v2/
